server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Uploads bis 50 MB erlauben (wie im Backend)
    client_max_body_size 50M;

    # API-Calls an den Spring-Boot-Container "app" weiterleiten
    location /docs      { proxy_pass http://app:8080; }
    location /session   { proxy_pass http://app:8080; }
    location /users     { proxy_pass http://app:8080; }

    location /documents/ { proxy_pass http://app:8080; }

    # Angular-Routing: alles andere bekommt index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
